// ARQUIVO COM TODAS AS BIBLIOTECAS E MACROS NECESCESSÁRIAS
// ! -> .h  ao invés de .hpp para identificar um arquivo biblioteca ou gabarito

#pragma once

#define GRAVIDADE 500.f
#define NoChaoAZUL false
#define NoChaoAMARELO false
#define DELTATIME 60.0f
#define JOGADORALTURA 100.f
#define JOGADORLARGURA 50.f
#define IDJOGADOR 1
#define IDINIMIGO 2
#define IDOBSTACULO 3
#define IDCARREGARSAVESTATE 11
#define IDFASESTATE 12
#define IDLEADERBOARDSTATE 13
#define IDMENUFASESSTATE 14
#define IDMENUINICIALSTATE 15
#define IDMENUJOGADORESSTATE 16
#define IDPAUSESTATE 17
#define IDPANTANOMALDITO 18
#define IDCASTELOASSOMBRADO 19