// ARQUIVO COM TODAS AS BIBLIOTECAS E MACROS NECESCESSÁRIAS
// ! -> .h  ao invés de .hpp para identificar um arquivo biblioteca ou gabarito

#pragma once

#define GRAVIDADE 500.f
#define NoChaoAZUL false
#define NoChaoAMARELO false
#define DELTATIME 300.0f
#define JOGADORALTURA 100.f
#define JOGADORLARGURA 50.f
#define IDJOGADOR 1
#define IDINIMIGO 2
#define IDOBSTACUlO 3
#define ID_PROJETIL 4

#define RAIO_PERSEGUIR_X 300.0f
//#define RAIO_PERSEGUIR_Y 200.0f
#define FAIXA_ALEATORIO 2

#define ALTURAMINION 30.0f
#define LARGURAMINION 30.0f

#define TAM_JOGADORX 35.0f
#define TAM_JOGADORY 60.0f
#define TAM_BORDA 3
#define LARGURA 1280
#define ALTURA 720
#define ESQUELETOALTURA 50.0f
#define ESQUELETOLARGURA 30.0f
#define ALCANCE 100.0f
#define VELOCIDADEX_ESQ 30.0f
#define VELOCIDADEY_ESQ 0.0f

#define DURAHANALTURA 80.0f
#define DURAHANLARGURA 65.0f
#define VELOCIDADEX_DU 150.0f
#define VELOCIDADEY_DU 0.0f

#define LARGURA_ESPINHO 20.0f
#define ALTURA_ESPINHO 40.0f

#define LARGURA_CANHAO 100.0f
#define ALTURA_CANHAO 50.0f

#define TAM_X_PROJETIL 10.0f
#define TAM_Y_PROJETIL 4.0f
#define VEL_X_P 150.0f
#define TAM_MAX_P 25

#define IDOBSTACULO 3
//#define IDPORTAL 20
#define IDCARREGARSAVESTATE 11
#define IDFASESTATE 12
#define IDLEADERBOARDSTATE 13
#define IDMENUFASESSTATE 14
#define IDMENUINICIALSTATE 15
#define IDMENUJOGADORESSTATE 16
#define IDPAUSESTATE 17
#define IDPANTANOMALDITO 18
#define IDCASTELOASSOMBRADO 19

#define TAM_X_BOLACANHAO
#define TAM_Y_BOLACANHAO
#define IDBOLACANHAO 30
#define TAM_MAX_BOLAS_CANHAO 5

//#define POSICAO_INICIAL_X 10
//#define POSICAO_INICIAL_Y 700
#define VELOCIDADE_PULO 200.0f
#define RAIO_ATAQUE 100.0f
#define ALTURACAIXA 100.0f